const KOSPI_QUANT_PACKAGE = {
    "server": {
        "krx_basis_date": "20260618",
        "dart_basis": "2026년 1분기보고서",
        "status": "NORMAL",
        "checked_at": "01:59:28"
    },
    "super_value": [
        {
            "rank": 1,
            "name": "매일홀딩스",
            "price": 10700,
            "market_cap": 1422,
            "pbr": 0.16,
            "pbr_r": 2,
            "per": 7.4,
            "per_r": 4,
            "pfcr": 5.3,
            "pfcr_r": 4,
            "psr": 0.26,
            "psr_r": 1,
            "avg_r": 2.8
        },
        {
            "rank": 2,
            "name": "한진중공업홀딩스",
            "price": 4815,
            "market_cap": 1421,
            "pbr": 0.28,
            "pbr_r": 12,
            "per": 4.01,
            "per_r": 2,
            "pfcr": 1.43,
            "pfcr_r": 1,
            "psr": 0.29,
            "psr_r": 2,
            "avg_r": 4.2
        },
        {
            "rank": 3,
            "name": "세원정공",
            "price": 11600,
            "market_cap": 1160,
            "pbr": 0.16,
            "pbr_r": 1,
            "per": 2.38,
            "per_r": 1,
            "pfcr": 2.88,
            "pfcr_r": 3,
            "psr": 0.65,
            "psr_r": 12,
            "avg_r": 4.2
        },
        {
            "rank": 4,
            "name": "LX하우시스",
            "price": 32800,
            "market_cap": 2941,
            "pbr": 0.34,
            "pbr_r": 19,
            "per": 9.66,
            "per_r": 8,
            "pfcr": 2.19,
            "pfcr_r": 2,
            "psr": 0.36,
            "psr_r": 4,
            "avg_r": 8.2
        },
        {
            "rank": 5,
            "name": "DSR",
            "price": 4240,
            "market_cap": 678,
            "pbr": 0.27,
            "pbr_r": 11,
            "per": 6.93,
            "per_r": 3,
            "pfcr": 11.96,
            "pfcr_r": 18,
            "psr": 0.89,
            "psr_r": 18,
            "avg_r": 12.5
        },
        {
            "rank": 6,
            "name": "HDC현대EP",
            "price": 3915,
            "market_cap": 1248,
            "pbr": 0.35,
            "pbr_r": 20,
            "per": 27.4,
            "per_r": 27,
            "pfcr": 7.01,
            "pfcr_r": 8,
            "psr": 0.49,
            "psr_r": 6,
            "avg_r": 15.2
        },
        {
            "rank": 7,
            "name": "동양",
            "price": 565,
            "market_cap": 1348,
            "pbr": 0.18,
            "pbr_r": 5,
            "per": 19.12,
            "per_r": 21,
            "pfcr": 9.73,
            "pfcr_r": 13,
            "psr": 1.08,
            "psr_r": 22,
            "avg_r": 15.2
        },
        {
            "rank": 8,
            "name": "이마트",
            "price": 87500,
            "market_cap": 24146,
            "pbr": 0.17,
            "pbr_r": 3,
            "per": 30.41,
            "per_r": 30,
            "pfcr": 17.32,
            "pfcr_r": 25,
            "psr": 0.34,
            "psr_r": 3,
            "avg_r": 15.2
        },
        {
            "rank": 9,
            "name": "매일유업",
            "price": 33300,
            "market_cap": 2551,
            "pbr": 0.4,
            "pbr_r": 24,
            "per": 13.5,
            "per_r": 15,
            "pfcr": 11.71,
            "pfcr_r": 17,
            "psr": 0.54,
            "psr_r": 7,
            "avg_r": 15.8
        },
        {
            "rank": 10,
            "name": "GS",
            "price": 71300,
            "market_cap": 66234,
            "pbr": 0.33,
            "pbr_r": 18,
            "per": 8.01,
            "per_r": 5,
            "pfcr": 13.78,
            "pfcr_r": 20,
            "psr": 0.97,
            "psr_r": 20,
            "avg_r": 15.8
        },
        {
            "rank": 11,
            "name": "CJ",
            "price": 183500,
            "market_cap": 53539,
            "pbr": 0.31,
            "pbr_r": 17,
            "per": 30.71,
            "per_r": 31,
            "pfcr": 11.06,
            "pfcr_r": 15,
            "psr": 0.47,
            "psr_r": 5,
            "avg_r": 17.0
        },
        {
            "rank": 12,
            "name": "유니크",
            "price": 4000,
            "market_cap": 772,
            "pbr": 0.55,
            "pbr_r": 36,
            "per": 16.25,
            "per_r": 16,
            "pfcr": 6.1,
            "pfcr_r": 6,
            "psr": 0.69,
            "psr_r": 14,
            "avg_r": 18.0
        },
        {
            "rank": 13,
            "name": "대원강업",
            "price": 4635,
            "market_cap": 2873,
            "pbr": 0.38,
            "pbr_r": 23,
            "per": 8.21,
            "per_r": 6,
            "pfcr": 22.19,
            "pfcr_r": 31,
            "psr": 0.66,
            "psr_r": 13,
            "avg_r": 18.2
        },
        {
            "rank": 14,
            "name": "에스에이티",
            "price": 1240,
            "market_cap": 324,
            "pbr": 0.31,
            "pbr_r": 16,
            "per": 18.75,
            "per_r": 20,
            "pfcr": 19.81,
            "pfcr_r": 27,
            "psr": 0.77,
            "psr_r": 15,
            "avg_r": 19.5
        },
        {
            "rank": 15,
            "name": "경방",
            "price": 8450,
            "market_cap": 2316,
            "pbr": 0.28,
            "pbr_r": 13,
            "per": 11.31,
            "per_r": 9,
            "pfcr": 17.15,
            "pfcr_r": 24,
            "psr": 2.09,
            "psr_r": 35,
            "avg_r": 20.2
        },
        {
            "rank": 16,
            "name": "종근당홀딩스",
            "price": 41100,
            "market_cap": 2059,
            "pbr": 0.22,
            "pbr_r": 6,
            "per": 11.5,
            "per_r": 11,
            "pfcr": 39.92,
            "pfcr_r": 50,
            "psr": 0.86,
            "psr_r": 16,
            "avg_r": 20.8
        },
        {
            "rank": 17,
            "name": "동국제강",
            "price": 9640,
            "market_cap": 4782,
            "pbr": 0.25,
            "pbr_r": 10,
            "per": 77.02,
            "per_r": 65,
            "pfcr": 7.0,
            "pfcr_r": 7,
            "psr": 0.56,
            "psr_r": 8,
            "avg_r": 22.5
        },
        {
            "rank": 18,
            "name": "대원산업",
            "price": 10830,
            "market_cap": 2170,
            "pbr": 0.36,
            "pbr_r": 21,
            "per": 11.39,
            "per_r": 10,
            "pfcr": 32.21,
            "pfcr_r": 40,
            "psr": 0.92,
            "psr_r": 19,
            "avg_r": 22.5
        },
        {
            "rank": 19,
            "name": "일양약품",
            "price": 8310,
            "market_cap": 1586,
            "pbr": 0.62,
            "pbr_r": 40,
            "per": 9.35,
            "per_r": 7,
            "pfcr": 6.04,
            "pfcr_r": 5,
            "psr": 2.44,
            "psr_r": 44,
            "avg_r": 24.0
        },
        {
            "rank": 20,
            "name": "LG헬로비전",
            "price": 2090,
            "market_cap": 1618,
            "pbr": 0.36,
            "pbr_r": 22,
            "per": 53.58,
            "per_r": 55,
            "pfcr": 10.82,
            "pfcr_r": 14,
            "psr": 0.63,
            "psr_r": 10,
            "avg_r": 25.2
        },
        {
            "rank": 21,
            "name": "선광",
            "price": 19080,
            "market_cap": 1259,
            "pbr": 0.29,
            "pbr_r": 14,
            "per": 13.35,
            "per_r": 14,
            "pfcr": 19.77,
            "pfcr_r": 26,
            "psr": 2.84,
            "psr_r": 47,
            "avg_r": 25.2
        },
        {
            "rank": 22,
            "name": "DL",
            "price": 52400,
            "market_cap": 10980,
            "pbr": 0.22,
            "pbr_r": 7,
            "per": 90.48,
            "per_r": 69,
            "pfcr": 8.76,
            "pfcr_r": 12,
            "psr": 0.86,
            "psr_r": 17,
            "avg_r": 26.2
        },
        {
            "rank": 23,
            "name": "HDC",
            "price": 20900,
            "market_cap": 12486,
            "pbr": 0.23,
            "pbr_r": 8,
            "per": 11.65,
            "per_r": 12,
            "pfcr": 105.81,
            "pfcr_r": 66,
            "psr": 0.99,
            "psr_r": 21,
            "avg_r": 26.8
        },
        {
            "rank": 24,
            "name": "에스텍",
            "price": 12020,
            "market_cap": 1311,
            "pbr": 0.54,
            "pbr_r": 35,
            "per": 16.57,
            "per_r": 17,
            "pfcr": 26.99,
            "pfcr_r": 35,
            "psr": 1.25,
            "psr_r": 23,
            "avg_r": 27.5
        },
        {
            "rank": 25,
            "name": "한일단조",
            "price": 2275,
            "market_cap": 748,
            "pbr": 0.51,
            "pbr_r": 32,
            "per": 27.68,
            "per_r": 28,
            "pfcr": 11.66,
            "pfcr_r": 16,
            "psr": 2.1,
            "psr_r": 36,
            "avg_r": 28.0
        },
        {
            "rank": 26,
            "name": "삼화왕관",
            "price": 25650,
            "market_cap": 552,
            "pbr": 0.46,
            "pbr_r": 28,
            "per": 20.13,
            "per_r": 22,
            "pfcr": 33.74,
            "pfcr_r": 42,
            "psr": 1.4,
            "psr_r": 26,
            "avg_r": 29.5
        },
        {
            "rank": 27,
            "name": "KB오토시스",
            "price": 3200,
            "market_cap": 368,
            "pbr": 0.3,
            "pbr_r": 15,
            "per": 16.83,
            "per_r": 18,
            "pfcr": 186.85,
            "pfcr_r": 74,
            "psr": 0.64,
            "psr_r": 11,
            "avg_r": 29.5
        },
        {
            "rank": 28,
            "name": "CJ대한통운",
            "price": 81400,
            "market_cap": 18569,
            "pbr": 0.42,
            "pbr_r": 27,
            "per": 48.94,
            "per_r": 54,
            "pfcr": 26.73,
            "pfcr_r": 34,
            "psr": 0.58,
            "psr_r": 9,
            "avg_r": 31.0
        },
        {
            "rank": 29,
            "name": "LG유플러스",
            "price": 15010,
            "market_cap": 63706,
            "pbr": 0.7,
            "pbr_r": 44,
            "per": 36.19,
            "per_r": 37,
            "pfcr": 12.67,
            "pfcr_r": 19,
            "psr": 1.67,
            "psr_r": 29,
            "avg_r": 32.2
        },
        {
            "rank": 30,
            "name": "영원무역홀딩스",
            "price": 176100,
            "market_cap": 22811,
            "pbr": 0.42,
            "pbr_r": 26,
            "per": 11.74,
            "per_r": 13,
            "pfcr": 87.14,
            "pfcr_r": 60,
            "psr": 2.11,
            "psr_r": 38,
            "avg_r": 34.2
        }
    ],
    "super_value_smallcap": [
        {
            "rank": 1,
            "name": "에스에이티",
            "price": 1240,
            "market_cap": 324,
            "pbr": 0.31,
            "pbr_r": 2,
            "per": 18.75,
            "per_r": 1,
            "pfcr": 19.81,
            "pfcr_r": 2,
            "psr": 0.77,
            "psr_r": 1,
            "avg_r": 1.5
        },
        {
            "rank": 2,
            "name": "플랜티넷",
            "price": 1968,
            "market_cap": 327,
            "pbr": 0.41,
            "pbr_r": 3,
            "per": 80.72,
            "per_r": 4,
            "pfcr": 8.65,
            "pfcr_r": 1,
            "psr": 3.1,
            "psr_r": 2,
            "avg_r": 2.5
        },
        {
            "rank": 3,
            "name": "이화산업",
            "price": 12380,
            "market_cap": 346,
            "pbr": 0.17,
            "pbr_r": 1,
            "per": 46.67,
            "per_r": 3,
            "pfcr": 88.68,
            "pfcr_r": 3,
            "psr": 3.14,
            "psr_r": 3,
            "avg_r": 2.5
        },
        {
            "rank": 4,
            "name": "이퓨쳐",
            "price": 4765,
            "market_cap": 227,
            "pbr": 0.99,
            "pbr_r": 4,
            "per": 37.16,
            "per_r": 2,
            "pfcr": 124.56,
            "pfcr_r": 4,
            "psr": 8.96,
            "psr_r": 4,
            "avg_r": 3.5
        }
    ],
    "momentum_value": [
        {
            "rank": 1,
            "name": "에스에이엠티",
            "price": 15950,
            "market_cap": 15949,
            "op_growth_qoq": 628.1,
            "op_qoq_r": 13,
            "op_growth_yoy": 1575.2,
            "op_yoy_r": 5,
            "ni_growth_qoq": 604.2,
            "ni_qoq_r": 8,
            "ni_growth_yoy": 1932.1,
            "ni_yoy_r": 6,
            "avg_r": 8.0
        },
        {
            "rank": 2,
            "name": "쇼박스",
            "price": 2415,
            "market_cap": 1512,
            "op_growth_qoq": 707.4,
            "op_qoq_r": 12,
            "op_growth_yoy": 1634.6,
            "op_yoy_r": 4,
            "ni_growth_qoq": 419.2,
            "ni_qoq_r": 13,
            "ni_growth_yoy": 1334.2,
            "ni_yoy_r": 9,
            "avg_r": 9.5
        },
        {
            "rank": 3,
            "name": "피델릭스",
            "price": 6000,
            "market_cap": 1987,
            "op_growth_qoq": 316.7,
            "op_qoq_r": 24,
            "op_growth_yoy": 793.8,
            "op_yoy_r": 10,
            "ni_growth_qoq": 318.9,
            "ni_qoq_r": 20,
            "ni_growth_yoy": 784.9,
            "ni_yoy_r": 13,
            "avg_r": 16.8
        },
        {
            "rank": 4,
            "name": "OCI",
            "price": 104600,
            "market_cap": 9364,
            "op_growth_qoq": 889.1,
            "op_qoq_r": 8,
            "op_growth_yoy": 171.6,
            "op_yoy_r": 26,
            "ni_growth_qoq": 612.3,
            "ni_qoq_r": 7,
            "ni_growth_yoy": 242.8,
            "ni_yoy_r": 31,
            "avg_r": 18.0
        },
        {
            "rank": 5,
            "name": "이수화학",
            "price": 14590,
            "market_cap": 3836,
            "op_growth_qoq": 845.8,
            "op_qoq_r": 10,
            "op_growth_yoy": 163349.3,
            "op_yoy_r": 1,
            "ni_growth_qoq": 193.4,
            "ni_qoq_r": 36,
            "ni_growth_yoy": 250.9,
            "ni_yoy_r": 30,
            "avg_r": 19.2
        },
        {
            "rank": 6,
            "name": "LX하우시스",
            "price": 32800,
            "market_cap": 2941,
            "op_growth_qoq": 258.7,
            "op_qoq_r": 31,
            "op_growth_yoy": 549.7,
            "op_yoy_r": 12,
            "ni_growth_qoq": 155.7,
            "ni_qoq_r": 44,
            "ni_growth_yoy": 1346.6,
            "ni_yoy_r": 8,
            "avg_r": 23.8
        },
        {
            "rank": 7,
            "name": "한일단조",
            "price": 2275,
            "market_cap": 748,
            "op_growth_qoq": 1359.0,
            "op_qoq_r": 6,
            "op_growth_yoy": 211.7,
            "op_yoy_r": 23,
            "ni_growth_qoq": 542.1,
            "ni_qoq_r": 11,
            "ni_growth_yoy": 119.8,
            "ni_yoy_r": 59,
            "avg_r": 24.8
        },
        {
            "rank": 8,
            "name": "삼성전자",
            "price": 362500,
            "market_cap": 21192759,
            "op_growth_qoq": 185.1,
            "op_qoq_r": 35,
            "op_growth_yoy": 756.1,
            "op_yoy_r": 11,
            "ni_growth_qoq": 140.4,
            "ni_qoq_r": 49,
            "ni_growth_yoy": 474.3,
            "ni_yoy_r": 15,
            "avg_r": 27.5
        },
        {
            "rank": 9,
            "name": "호텔신라",
            "price": 57600,
            "market_cap": 22606,
            "op_growth_qoq": 595.8,
            "op_qoq_r": 14,
            "op_growth_yoy": 926.4,
            "op_yoy_r": 8,
            "ni_growth_qoq": 136.1,
            "ni_qoq_r": 51,
            "ni_growth_yoy": 197.1,
            "ni_yoy_r": 37,
            "avg_r": 27.5
        },
        {
            "rank": 10,
            "name": "SK스퀘어",
            "price": 1700000,
            "market_cap": 2243292,
            "op_growth_qoq": 167.2,
            "op_qoq_r": 38,
            "op_growth_yoy": 400.5,
            "op_yoy_r": 15,
            "ni_growth_qoq": 155.6,
            "ni_qoq_r": 45,
            "ni_growth_yoy": 419.4,
            "ni_yoy_r": 17,
            "avg_r": 28.8
        },
        {
            "rank": 11,
            "name": "동국제강",
            "price": 9640,
            "market_cap": 4782,
            "op_growth_qoq": 2886.7,
            "op_qoq_r": 3,
            "op_growth_yoy": 403.9,
            "op_yoy_r": 14,
            "ni_growth_qoq": 146.1,
            "ni_qoq_r": 48,
            "ni_growth_yoy": 153.3,
            "ni_yoy_r": 50,
            "avg_r": 28.8
        },
        {
            "rank": 12,
            "name": "큐에스아이",
            "price": 9580,
            "market_cap": 888,
            "op_growth_qoq": 455.9,
            "op_qoq_r": 16,
            "op_growth_yoy": 1698.3,
            "op_yoy_r": 3,
            "ni_growth_qoq": 45.9,
            "ni_qoq_r": 88,
            "ni_growth_yoy": 1064.7,
            "ni_yoy_r": 10,
            "avg_r": 29.2
        },
        {
            "rank": 13,
            "name": "티에스이",
            "price": 249000,
            "market_cap": 27542,
            "op_growth_qoq": 112.4,
            "op_qoq_r": 55,
            "op_growth_yoy": 1247.0,
            "op_yoy_r": 7,
            "ni_growth_qoq": 82.5,
            "ni_qoq_r": 78,
            "ni_growth_yoy": 2133.3,
            "ni_yoy_r": 4,
            "avg_r": 36.0
        },
        {
            "rank": 14,
            "name": "CR홀딩스",
            "price": 4755,
            "market_cap": 2229,
            "op_growth_qoq": 302.9,
            "op_qoq_r": 26,
            "op_growth_yoy": 52.1,
            "op_yoy_r": 55,
            "ni_growth_qoq": 137.7,
            "ni_qoq_r": 50,
            "ni_growth_yoy": 716.4,
            "ni_yoy_r": 14,
            "avg_r": 36.2
        },
        {
            "rank": 15,
            "name": "유니크",
            "price": 4000,
            "market_cap": 772,
            "op_growth_qoq": 347.2,
            "op_qoq_r": 21,
            "op_growth_yoy": 54.7,
            "op_yoy_r": 52,
            "ni_growth_qoq": 436.8,
            "ni_qoq_r": 12,
            "ni_growth_yoy": 115.0,
            "ni_yoy_r": 61,
            "avg_r": 36.5
        },
        {
            "rank": 16,
            "name": "진흥기업",
            "price": 892,
            "market_cap": 1297,
            "op_growth_qoq": 141.6,
            "op_qoq_r": 45,
            "op_growth_yoy": 835.7,
            "op_yoy_r": 9,
            "ni_growth_qoq": 135.3,
            "ni_qoq_r": 52,
            "ni_growth_yoy": 178.5,
            "ni_yoy_r": 43,
            "avg_r": 37.2
        },
        {
            "rank": 17,
            "name": "조선내화",
            "price": 14880,
            "market_cap": 1764,
            "op_growth_qoq": 293.5,
            "op_qoq_r": 27,
            "op_growth_yoy": 54.3,
            "op_yoy_r": 53,
            "ni_growth_qoq": 597.7,
            "ni_qoq_r": 9,
            "ni_growth_yoy": 115.1,
            "ni_yoy_r": 60,
            "avg_r": 37.2
        },
        {
            "rank": 18,
            "name": "아스트",
            "price": 569,
            "market_cap": 2362,
            "op_growth_qoq": 988.1,
            "op_qoq_r": 7,
            "op_growth_yoy": 18.2,
            "op_yoy_r": 84,
            "ni_growth_qoq": 250.0,
            "ni_qoq_r": 25,
            "ni_growth_yoy": 201.4,
            "ni_yoy_r": 36,
            "avg_r": 38.0
        },
        {
            "rank": 19,
            "name": "남성",
            "price": 7000,
            "market_cap": 253,
            "op_growth_qoq": 304.7,
            "op_qoq_r": 25,
            "op_growth_yoy": -27.5,
            "op_yoy_r": 124,
            "ni_growth_qoq": 815.2,
            "ni_qoq_r": 4,
            "ni_growth_yoy": 9441.3,
            "ni_yoy_r": 2,
            "avg_r": 38.8
        },
        {
            "rank": 20,
            "name": "에스폴리텍",
            "price": 1116,
            "market_cap": 182,
            "op_growth_qoq": 129.6,
            "op_qoq_r": 51,
            "op_growth_yoy": 117.1,
            "op_yoy_r": 33,
            "ni_growth_qoq": 150.1,
            "ni_qoq_r": 47,
            "ni_growth_yoy": 254.4,
            "ni_yoy_r": 29,
            "avg_r": 40.0
        },
        {
            "rank": 21,
            "name": "엘컴텍",
            "price": 2780,
            "market_cap": 469,
            "op_growth_qoq": 159.9,
            "op_qoq_r": 40,
            "op_growth_yoy": 135.7,
            "op_yoy_r": 30,
            "ni_growth_qoq": 157.6,
            "ni_qoq_r": 43,
            "ni_growth_yoy": 149.1,
            "ni_yoy_r": 51,
            "avg_r": 41.0
        },
        {
            "rank": 22,
            "name": "램테크놀러지",
            "price": 3080,
            "market_cap": 440,
            "op_growth_qoq": 138.9,
            "op_qoq_r": 47,
            "op_growth_yoy": 192.7,
            "op_yoy_r": 25,
            "ni_growth_qoq": 102.4,
            "ni_qoq_r": 68,
            "ni_growth_yoy": 188.8,
            "ni_yoy_r": 40,
            "avg_r": 45.0
        },
        {
            "rank": 23,
            "name": "두산",
            "price": 1634000,
            "market_cap": 264607,
            "op_growth_qoq": 23.8,
            "op_qoq_r": 94,
            "op_growth_yoy": 71.7,
            "op_yoy_r": 42,
            "ni_growth_qoq": 195.4,
            "ni_qoq_r": 34,
            "ni_growth_yoy": 799.1,
            "ni_yoy_r": 12,
            "avg_r": 45.5
        },
        {
            "rank": 24,
            "name": "대우건설",
            "price": 22950,
            "market_cap": 94303,
            "op_growth_qoq": 123.1,
            "op_qoq_r": 52,
            "op_growth_yoy": 68.9,
            "op_yoy_r": 44,
            "ni_growth_qoq": 122.3,
            "ni_qoq_r": 60,
            "ni_growth_yoy": 237.9,
            "ni_yoy_r": 32,
            "avg_r": 47.0
        },
        {
            "rank": 25,
            "name": "한온시스템",
            "price": 4640,
            "market_cap": 47618,
            "op_growth_qoq": 8.3,
            "op_qoq_r": 103,
            "op_growth_yoy": 361.1,
            "op_yoy_r": 16,
            "ni_growth_qoq": 131.4,
            "ni_qoq_r": 54,
            "ni_growth_yoy": 398.6,
            "ni_yoy_r": 18,
            "avg_r": 47.8
        },
        {
            "rank": 26,
            "name": "화천기계",
            "price": 2980,
            "market_cap": 655,
            "op_growth_qoq": 45.5,
            "op_qoq_r": 78,
            "op_growth_yoy": 39.1,
            "op_yoy_r": 64,
            "ni_growth_qoq": 314.5,
            "ni_qoq_r": 22,
            "ni_growth_yoy": 255.2,
            "ni_yoy_r": 28,
            "avg_r": 48.0
        },
        {
            "rank": 27,
            "name": "GS",
            "price": 71300,
            "market_cap": 66234,
            "op_growth_qoq": 62.1,
            "op_qoq_r": 70,
            "op_growth_yoy": 56.7,
            "op_yoy_r": 51,
            "ni_growth_qoq": 230.0,
            "ni_qoq_r": 31,
            "ni_growth_yoy": 183.6,
            "ni_yoy_r": 41,
            "avg_r": 48.2
        },
        {
            "rank": 28,
            "name": "NHN벅스",
            "price": 3220,
            "market_cap": 477,
            "op_growth_qoq": 109.2,
            "op_qoq_r": 58,
            "op_growth_yoy": 128.0,
            "op_yoy_r": 31,
            "ni_growth_qoq": 109.9,
            "ni_qoq_r": 66,
            "ni_growth_yoy": 191.2,
            "ni_yoy_r": 39,
            "avg_r": 48.5
        },
        {
            "rank": 29,
            "name": "DL",
            "price": 52400,
            "market_cap": 10980,
            "op_growth_qoq": 858.1,
            "op_qoq_r": 9,
            "op_growth_yoy": 7.1,
            "op_yoy_r": 99,
            "ni_growth_qoq": 169.3,
            "ni_qoq_r": 39,
            "ni_growth_yoy": 162.3,
            "ni_yoy_r": 47,
            "avg_r": 48.5
        },
        {
            "rank": 30,
            "name": "코스모화학",
            "price": 12370,
            "market_cap": 4751,
            "op_growth_qoq": 182.1,
            "op_qoq_r": 36,
            "op_growth_yoy": 528.7,
            "op_yoy_r": 13,
            "ni_growth_qoq": 98.6,
            "ni_qoq_r": 70,
            "ni_growth_yoy": 66.6,
            "ni_yoy_r": 78,
            "avg_r": 49.2
        }
    ],
    "momentum_value_smallcap": [
        {
            "rank": 1,
            "name": "남성",
            "price": 7000,
            "market_cap": 253,
            "op_growth_qoq": 304.7,
            "op_qoq_r": 2,
            "op_growth_yoy": -27.5,
            "op_yoy_r": 6,
            "ni_growth_qoq": 815.2,
            "ni_qoq_r": 1,
            "ni_growth_yoy": 9441.3,
            "ni_yoy_r": 1,
            "avg_r": 2.5
        },
        {
            "rank": 2,
            "name": "에스폴리텍",
            "price": 1116,
            "market_cap": 182,
            "op_growth_qoq": 129.6,
            "op_qoq_r": 4,
            "op_growth_yoy": 117.1,
            "op_yoy_r": 3,
            "ni_growth_qoq": 150.1,
            "ni_qoq_r": 2,
            "ni_growth_yoy": 254.4,
            "ni_yoy_r": 2,
            "avg_r": 2.8
        },
        {
            "rank": 3,
            "name": "이화산업",
            "price": 12380,
            "market_cap": 346,
            "op_growth_qoq": 170.0,
            "op_qoq_r": 3,
            "op_growth_yoy": 26.0,
            "op_yoy_r": 5,
            "ni_growth_qoq": 130.4,
            "ni_qoq_r": 3,
            "ni_growth_yoy": 108.4,
            "ni_yoy_r": 5,
            "avg_r": 4.0
        },
        {
            "rank": 4,
            "name": "조아제약",
            "price": 587,
            "market_cap": 181,
            "op_growth_qoq": 25.4,
            "op_qoq_r": 6,
            "op_growth_yoy": 46.8,
            "op_yoy_r": 4,
            "ni_growth_qoq": 95.3,
            "ni_qoq_r": 6,
            "ni_growth_yoy": 93.2,
            "ni_yoy_r": 6,
            "avg_r": 5.5
        },
        {
            "rank": 5,
            "name": "국일신동",
            "price": 1508,
            "market_cap": 167,
            "op_growth_qoq": -23.7,
            "op_qoq_r": 7,
            "op_growth_yoy": 8415.3,
            "op_yoy_r": 1,
            "ni_growth_qoq": -43.8,
            "ni_qoq_r": 11,
            "ni_growth_yoy": 131.3,
            "ni_yoy_r": 4,
            "avg_r": 5.8
        },
        {
            "rank": 6,
            "name": "에스에이티",
            "price": 1240,
            "market_cap": 324,
            "op_growth_qoq": -61.0,
            "op_qoq_r": 9,
            "op_growth_yoy": 233.4,
            "op_yoy_r": 2,
            "ni_growth_qoq": -36.7,
            "ni_qoq_r": 10,
            "ni_growth_yoy": 212.0,
            "ni_yoy_r": 3,
            "avg_r": 6.0
        },
        {
            "rank": 7,
            "name": "플랜티넷",
            "price": 1968,
            "market_cap": 327,
            "op_growth_qoq": 417.3,
            "op_qoq_r": 1,
            "op_growth_yoy": -85.8,
            "op_yoy_r": 9,
            "ni_growth_qoq": 126.1,
            "ni_qoq_r": 4,
            "ni_growth_yoy": -84.2,
            "ni_yoy_r": 10,
            "avg_r": 6.0
        },
        {
            "rank": 8,
            "name": "파인테크닉스",
            "price": 1220,
            "market_cap": 291,
            "op_growth_qoq": 26.8,
            "op_qoq_r": 5,
            "op_growth_yoy": -43.2,
            "op_yoy_r": 7,
            "ni_growth_qoq": 78.8,
            "ni_qoq_r": 7,
            "ni_growth_yoy": 1.4,
            "ni_yoy_r": 9,
            "avg_r": 7.0
        },
        {
            "rank": 9,
            "name": "이퓨쳐",
            "price": 4765,
            "market_cap": 227,
            "op_growth_qoq": -81.2,
            "op_qoq_r": 10,
            "op_growth_yoy": -59.7,
            "op_yoy_r": 8,
            "ni_growth_qoq": -12.5,
            "ni_qoq_r": 9,
            "ni_growth_yoy": 49.6,
            "ni_yoy_r": 8,
            "avg_r": 8.8
        },
        {
            "rank": 10,
            "name": "우리엔터프라이즈",
            "price": 790,
            "market_cap": 207,
            "op_growth_qoq": -64100.4,
            "op_qoq_r": 12,
            "op_growth_yoy": -683.7,
            "op_yoy_r": 12,
            "ni_growth_qoq": 95.8,
            "ni_qoq_r": 5,
            "ni_growth_yoy": 83.4,
            "ni_yoy_r": 7,
            "avg_r": 9.0
        },
        {
            "rank": 11,
            "name": "에넥스",
            "price": 1577,
            "market_cap": 186,
            "op_growth_qoq": -32.1,
            "op_qoq_r": 8,
            "op_growth_yoy": -277.4,
            "op_yoy_r": 11,
            "ni_growth_qoq": 3.2,
            "ni_qoq_r": 8,
            "ni_growth_yoy": -309.3,
            "ni_yoy_r": 12,
            "avg_r": 9.8
        },
        {
            "rank": 12,
            "name": "티엔엔터테인먼트",
            "price": 899,
            "market_cap": 289,
            "op_growth_qoq": -181.5,
            "op_qoq_r": 11,
            "op_growth_yoy": -143.2,
            "op_yoy_r": 10,
            "ni_growth_qoq": -191.6,
            "ni_qoq_r": 12,
            "ni_growth_yoy": -232.9,
            "ni_yoy_r": 11,
            "avg_r": 11.0
        }
    ],
    "fscore_value": [
        {
            "rank": 1,
            "name": "동국홀딩스",
            "price": 2015,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.16
        },
        {
            "rank": 2,
            "name": "세원정공",
            "price": 11600,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.16
        },
        {
            "rank": 3,
            "name": "SJM홀딩스",
            "price": 3490,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.16
        },
        {
            "rank": 4,
            "name": "매일홀딩스",
            "price": 10700,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.16
        },
        {
            "rank": 5,
            "name": "이화산업",
            "price": 12380,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.17
        },
        {
            "rank": 6,
            "name": "이마트",
            "price": 87500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.17
        },
        {
            "rank": 7,
            "name": "DL",
            "price": 52400,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.22
        },
        {
            "rank": 8,
            "name": "종근당홀딩스",
            "price": 41100,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.22
        },
        {
            "rank": 9,
            "name": "인터지스",
            "price": 2155,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.22
        },
        {
            "rank": 10,
            "name": "한일홀딩스",
            "price": 17320,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.23
        },
        {
            "rank": 11,
            "name": "HDC",
            "price": 20900,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.23
        },
        {
            "rank": 12,
            "name": "동국제강",
            "price": 9640,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.25
        },
        {
            "rank": 13,
            "name": "CR홀딩스",
            "price": 4755,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.27
        },
        {
            "rank": 14,
            "name": "DSR",
            "price": 4240,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.27
        },
        {
            "rank": 15,
            "name": "케이피에프",
            "price": 4340,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.27
        },
        {
            "rank": 16,
            "name": "경방",
            "price": 8450,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.28
        },
        {
            "rank": 17,
            "name": "한진중공업홀딩스",
            "price": 4815,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.28
        },
        {
            "rank": 18,
            "name": "선광",
            "price": 19080,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.29
        },
        {
            "rank": 19,
            "name": "LX홀딩스",
            "price": 7990,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.3
        },
        {
            "rank": 20,
            "name": "KB오토시스",
            "price": 3200,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.3
        },
        {
            "rank": 21,
            "name": "피에이치에이",
            "price": 12490,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.3
        },
        {
            "rank": 22,
            "name": "CJ",
            "price": 183500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.31
        },
        {
            "rank": 23,
            "name": "에스에이티",
            "price": 1240,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.31
        },
        {
            "rank": 24,
            "name": "GS",
            "price": 71300,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.33
        },
        {
            "rank": 25,
            "name": "LX하우시스",
            "price": 32800,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.34
        },
        {
            "rank": 26,
            "name": "HDC현대EP",
            "price": 3915,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.35
        },
        {
            "rank": 27,
            "name": "LG헬로비전",
            "price": 2090,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.36
        },
        {
            "rank": 28,
            "name": "대원산업",
            "price": 10830,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.36
        },
        {
            "rank": 29,
            "name": "대원강업",
            "price": 4635,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.38
        },
        {
            "rank": 30,
            "name": "스카이라이프",
            "price": 4465,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.39
        }
    ],
    "ncav_value": [
        {
            "rank": 1,
            "name": "SJM홀딩스",
            "price": 3490,
            "ncav": 2026,
            "market_cap": 521,
            "quarter_net_income": 78,
            "gpa": 3.5,
            "debt_ratio": 4.9
        },
        {
            "rank": 2,
            "name": "세원정공",
            "price": 11600,
            "ncav": 3439,
            "market_cap": 1160,
            "quarter_net_income": 487,
            "gpa": 4.0,
            "debt_ratio": 9.5
        },
        {
            "rank": 3,
            "name": "매일홀딩스",
            "price": 10700,
            "ncav": 2992,
            "market_cap": 1422,
            "quarter_net_income": 192,
            "gpa": 11.6,
            "debt_ratio": 24.5
        },
        {
            "rank": 4,
            "name": "대원산업",
            "price": 10830,
            "ncav": 4211,
            "market_cap": 2170,
            "quarter_net_income": 190,
            "gpa": 2.5,
            "debt_ratio": 1.7
        },
        {
            "rank": 5,
            "name": "모토닉",
            "price": 10010,
            "ncav": 3780,
            "market_cap": 2175,
            "quarter_net_income": 57,
            "gpa": 1.7,
            "debt_ratio": 0.0
        },
        {
            "rank": 6,
            "name": "신라교역",
            "price": 9110,
            "ncav": 2280,
            "market_cap": 1457,
            "quarter_net_income": 117,
            "gpa": 2.6,
            "debt_ratio": 6.6
        },
        {
            "rank": 7,
            "name": "에스텍",
            "price": 12020,
            "ncav": 1896,
            "market_cap": 1311,
            "quarter_net_income": 79,
            "gpa": 4.3,
            "debt_ratio": 43.5
        },
        {
            "rank": 8,
            "name": "NH농우바이오",
            "price": 7140,
            "ncav": 1554,
            "market_cap": 1144,
            "quarter_net_income": 64,
            "gpa": 5.8,
            "debt_ratio": 8.1
        },
        {
            "rank": 9,
            "name": "영원무역홀딩스",
            "price": 176100,
            "ncav": 30738,
            "market_cap": 22811,
            "quarter_net_income": 1942,
            "gpa": 5.8,
            "debt_ratio": 7.8
        },
        {
            "rank": 10,
            "name": "피에이치에이",
            "price": 12490,
            "ncav": 3367,
            "market_cap": 2622,
            "quarter_net_income": 182,
            "gpa": 3.2,
            "debt_ratio": 1.9
        },
        {
            "rank": 11,
            "name": "매일유업",
            "price": 33300,
            "ncav": 2985,
            "market_cap": 2551,
            "quarter_net_income": 189,
            "gpa": 11.1,
            "debt_ratio": 31.1
        },
        {
            "rank": 12,
            "name": "KT나스미디어",
            "price": 10140,
            "ncav": 1346,
            "market_cap": 1173,
            "quarter_net_income": 36,
            "gpa": null,
            "debt_ratio": 97.4
        },
        {
            "rank": 13,
            "name": "케이티알파",
            "price": 4490,
            "ncav": 2435,
            "market_cap": 2200,
            "quarter_net_income": 114,
            "gpa": 3.9,
            "debt_ratio": 57.9
        },
        {
            "rank": 14,
            "name": "진흥기업",
            "price": 892,
            "ncav": 1369,
            "market_cap": 1297,
            "quarter_net_income": 94,
            "gpa": 3.5,
            "debt_ratio": 5.4
        },
        {
            "rank": 15,
            "name": "멀티캠퍼스",
            "price": 24450,
            "ncav": 1538,
            "market_cap": 1449,
            "quarter_net_income": 15,
            "gpa": 5.3,
            "debt_ratio": 41.1
        },
        {
            "rank": 16,
            "name": "HDC현대EP",
            "price": 3915,
            "ncav": 1266,
            "market_cap": 1248,
            "quarter_net_income": 45,
            "gpa": 3.8,
            "debt_ratio": 45.0
        }
    ],
    "ncav_value_gpa": [
        {
            "rank": 1,
            "name": "SJM홀딩스",
            "price": 3490,
            "ncav": 2026,
            "market_cap": 521,
            "quarter_net_income": 78,
            "gpa": 3.5,
            "debt_ratio": 4.9
        },
        {
            "rank": 2,
            "name": "세원정공",
            "price": 11600,
            "ncav": 3439,
            "market_cap": 1160,
            "quarter_net_income": 487,
            "gpa": 4.0,
            "debt_ratio": 9.5
        },
        {
            "rank": 3,
            "name": "매일홀딩스",
            "price": 10700,
            "ncav": 2992,
            "market_cap": 1422,
            "quarter_net_income": 192,
            "gpa": 11.6,
            "debt_ratio": 24.5
        },
        {
            "rank": 4,
            "name": "에스텍",
            "price": 12020,
            "ncav": 1896,
            "market_cap": 1311,
            "quarter_net_income": 79,
            "gpa": 4.3,
            "debt_ratio": 43.5
        },
        {
            "rank": 5,
            "name": "NH농우바이오",
            "price": 7140,
            "ncav": 1554,
            "market_cap": 1144,
            "quarter_net_income": 64,
            "gpa": 5.8,
            "debt_ratio": 8.1
        },
        {
            "rank": 6,
            "name": "영원무역홀딩스",
            "price": 176100,
            "ncav": 30738,
            "market_cap": 22811,
            "quarter_net_income": 1942,
            "gpa": 5.8,
            "debt_ratio": 7.8
        },
        {
            "rank": 7,
            "name": "피에이치에이",
            "price": 12490,
            "ncav": 3367,
            "market_cap": 2622,
            "quarter_net_income": 182,
            "gpa": 3.2,
            "debt_ratio": 1.9
        },
        {
            "rank": 8,
            "name": "매일유업",
            "price": 33300,
            "ncav": 2985,
            "market_cap": 2551,
            "quarter_net_income": 189,
            "gpa": 11.1,
            "debt_ratio": 31.1
        },
        {
            "rank": 9,
            "name": "케이티알파",
            "price": 4490,
            "ncav": 2435,
            "market_cap": 2200,
            "quarter_net_income": 114,
            "gpa": 3.9,
            "debt_ratio": 57.9
        },
        {
            "rank": 10,
            "name": "진흥기업",
            "price": 892,
            "ncav": 1369,
            "market_cap": 1297,
            "quarter_net_income": 94,
            "gpa": 3.5,
            "debt_ratio": 5.4
        },
        {
            "rank": 11,
            "name": "멀티캠퍼스",
            "price": 24450,
            "ncav": 1538,
            "market_cap": 1449,
            "quarter_net_income": 15,
            "gpa": 5.3,
            "debt_ratio": 41.1
        },
        {
            "rank": 12,
            "name": "HDC현대EP",
            "price": 3915,
            "ncav": 1266,
            "market_cap": 1248,
            "quarter_net_income": 45,
            "gpa": 3.8,
            "debt_ratio": 45.0
        }
    ]
};
