const KOSPI_QUANT_PACKAGE = {
    "server": {
        "krx_basis_date": "20260618",
        "dart_basis": "2026년 1분기보고서",
        "status": "NORMAL",
        "checked_at": "03:52:10"
    },
    "super_value": [
        {
            "rank": 1,
            "name": "한진중공업홀딩스",
            "price": 4815,
            "pbr": 0.28,
            "pbr_r": 15,
            "per": 1.0,
            "per_r": 1,
            "pfcr": 0.33,
            "pfcr_r": 1,
            "psr": 0.07,
            "psr_r": 1,
            "avg_r": 4.5
        },
        {
            "rank": 2,
            "name": "SJM홀딩스",
            "price": 3490,
            "pbr": 0.16,
            "pbr_r": 1,
            "per": 1.66,
            "per_r": 2,
            "pfcr": 1.23,
            "pfcr_r": 4,
            "psr": 0.24,
            "psr_r": 16,
            "avg_r": 5.8
        },
        {
            "rank": 3,
            "name": "LX하우시스",
            "price": 32800,
            "pbr": 0.34,
            "pbr_r": 20,
            "per": 2.42,
            "per_r": 8,
            "pfcr": 0.46,
            "pfcr_r": 2,
            "psr": 0.09,
            "psr_r": 4,
            "avg_r": 8.5
        },
        {
            "rank": 4,
            "name": "DSR",
            "price": 4240,
            "pbr": 0.27,
            "pbr_r": 13,
            "per": 1.73,
            "per_r": 3,
            "pfcr": 1.75,
            "pfcr_r": 10,
            "psr": 0.22,
            "psr_r": 15,
            "avg_r": 10.2
        },
        {
            "rank": 5,
            "name": "종근당홀딩스",
            "price": 41100,
            "pbr": 0.22,
            "pbr_r": 7,
            "per": 2.88,
            "per_r": 10,
            "pfcr": 1.95,
            "pfcr_r": 14,
            "psr": 0.21,
            "psr_r": 13,
            "avg_r": 11.0
        },
        {
            "rank": 6,
            "name": "대원강업",
            "price": 4635,
            "pbr": 0.38,
            "pbr_r": 23,
            "per": 2.05,
            "per_r": 5,
            "pfcr": 1.79,
            "pfcr_r": 11,
            "psr": 0.17,
            "psr_r": 11,
            "avg_r": 12.5
        },
        {
            "rank": 7,
            "name": "이마트",
            "price": 87500,
            "pbr": 0.17,
            "pbr_r": 4,
            "per": 7.6,
            "per_r": 26,
            "pfcr": 2.35,
            "pfcr_r": 18,
            "psr": 0.08,
            "psr_r": 2,
            "avg_r": 12.5
        },
        {
            "rank": 8,
            "name": "GS",
            "price": 71300,
            "pbr": 0.33,
            "pbr_r": 19,
            "per": 2.0,
            "per_r": 4,
            "pfcr": 2.02,
            "pfcr_r": 16,
            "psr": 0.24,
            "psr_r": 17,
            "avg_r": 14.0
        },
        {
            "rank": 9,
            "name": "HDC현대EP",
            "price": 3915,
            "pbr": 0.35,
            "pbr_r": 21,
            "per": 6.85,
            "per_r": 23,
            "pfcr": 1.55,
            "pfcr_r": 7,
            "psr": 0.12,
            "psr_r": 6,
            "avg_r": 14.2
        },
        {
            "rank": 10,
            "name": "동양",
            "price": 565,
            "pbr": 0.18,
            "pbr_r": 6,
            "per": 4.78,
            "per_r": 15,
            "pfcr": 2.19,
            "pfcr_r": 17,
            "psr": 0.27,
            "psr_r": 20,
            "avg_r": 14.5
        },
        {
            "rank": 11,
            "name": "CJ",
            "price": 183500,
            "pbr": 0.31,
            "pbr_r": 18,
            "per": 7.68,
            "per_r": 27,
            "pfcr": 1.68,
            "pfcr_r": 9,
            "psr": 0.12,
            "psr_r": 5,
            "avg_r": 14.8
        },
        {
            "rank": 12,
            "name": "세원정공",
            "price": 11600,
            "pbr": 0.16,
            "pbr_r": 2,
            "per": 2.38,
            "per_r": 7,
            "pfcr": 1.92,
            "pfcr_r": 13,
            "psr": 0.65,
            "psr_r": 45,
            "avg_r": 16.8
        },
        {
            "rank": 13,
            "name": "인터지스",
            "price": 2155,
            "pbr": 0.22,
            "pbr_r": 8,
            "per": 5.52,
            "per_r": 18,
            "pfcr": 9.88,
            "pfcr_r": 50,
            "psr": 0.08,
            "psr_r": 3,
            "avg_r": 19.8
        },
        {
            "rank": 14,
            "name": "LG헬로비전",
            "price": 2090,
            "pbr": 0.36,
            "pbr_r": 22,
            "per": 13.4,
            "per_r": 46,
            "pfcr": 1.18,
            "pfcr_r": 3,
            "psr": 0.16,
            "psr_r": 10,
            "avg_r": 20.2
        },
        {
            "rank": 15,
            "name": "동국제강",
            "price": 9640,
            "pbr": 0.25,
            "pbr_r": 12,
            "per": 19.25,
            "per_r": 56,
            "pfcr": 1.43,
            "pfcr_r": 5,
            "psr": 0.14,
            "psr_r": 8,
            "avg_r": 20.2
        },
        {
            "rank": 16,
            "name": "경방",
            "price": 8450,
            "pbr": 0.28,
            "pbr_r": 16,
            "per": 2.83,
            "per_r": 9,
            "pfcr": 4.03,
            "pfcr_r": 24,
            "psr": 0.52,
            "psr_r": 35,
            "avg_r": 21.0
        },
        {
            "rank": 17,
            "name": "HDC",
            "price": 20900,
            "pbr": 0.23,
            "pbr_r": 10,
            "per": 2.91,
            "per_r": 11,
            "pfcr": 8.92,
            "pfcr_r": 45,
            "psr": 0.25,
            "psr_r": 18,
            "avg_r": 21.0
        },
        {
            "rank": 18,
            "name": "일양약품",
            "price": 8310,
            "pbr": 0.62,
            "pbr_r": 35,
            "per": 2.34,
            "per_r": 6,
            "pfcr": 1.5,
            "pfcr_r": 6,
            "psr": 0.61,
            "psr_r": 44,
            "avg_r": 22.8
        },
        {
            "rank": 19,
            "name": "DL",
            "price": 52400,
            "pbr": 0.22,
            "pbr_r": 9,
            "per": 22.62,
            "per_r": 60,
            "pfcr": 1.57,
            "pfcr_r": 8,
            "psr": 0.21,
            "psr_r": 14,
            "avg_r": 22.8
        },
        {
            "rank": 20,
            "name": "삼화왕관",
            "price": 25650,
            "pbr": 0.46,
            "pbr_r": 27,
            "per": 5.03,
            "per_r": 17,
            "pfcr": 4.8,
            "pfcr_r": 30,
            "psr": 0.35,
            "psr_r": 24,
            "avg_r": 24.5
        },
        {
            "rank": 21,
            "name": "CJ대한통운",
            "price": 81400,
            "pbr": 0.42,
            "pbr_r": 26,
            "per": 12.23,
            "per_r": 45,
            "pfcr": 2.82,
            "pfcr_r": 19,
            "psr": 0.14,
            "psr_r": 9,
            "avg_r": 24.8
        },
        {
            "rank": 22,
            "name": "DL이앤씨",
            "price": 79200,
            "pbr": 0.57,
            "pbr_r": 33,
            "per": 4.78,
            "per_r": 16,
            "pfcr": 4.49,
            "pfcr_r": 28,
            "psr": 0.44,
            "psr_r": 29,
            "avg_r": 26.5
        },
        {
            "rank": 23,
            "name": "LG유플러스",
            "price": 15010,
            "pbr": 0.7,
            "pbr_r": 39,
            "per": 9.05,
            "per_r": 32,
            "pfcr": 1.84,
            "pfcr_r": 12,
            "psr": 0.42,
            "psr_r": 27,
            "avg_r": 27.5
        },
        {
            "rank": 24,
            "name": "효성티앤씨",
            "price": 323000,
            "pbr": 0.68,
            "pbr_r": 38,
            "per": 6.87,
            "per_r": 24,
            "pfcr": 6.36,
            "pfcr_r": 37,
            "psr": 0.17,
            "psr_r": 12,
            "avg_r": 27.8
        },
        {
            "rank": 25,
            "name": "영원무역홀딩스",
            "price": 176100,
            "pbr": 0.42,
            "pbr_r": 24,
            "per": 2.94,
            "per_r": 12,
            "pfcr": 6.81,
            "pfcr_r": 40,
            "psr": 0.53,
            "psr_r": 36,
            "avg_r": 28.0
        },
        {
            "rank": 26,
            "name": "한일홀딩스",
            "price": 17320,
            "pbr": 0.23,
            "pbr_r": 11,
            "per": 21.97,
            "per_r": 59,
            "pfcr": 3.91,
            "pfcr_r": 23,
            "psr": 0.34,
            "psr_r": 23,
            "avg_r": 29.0
        },
        {
            "rank": 27,
            "name": "CR홀딩스",
            "price": 4755,
            "pbr": 0.27,
            "pbr_r": 14,
            "per": 6.95,
            "per_r": 25,
            "pfcr": 13.92,
            "pfcr_r": 57,
            "psr": 0.27,
            "psr_r": 21,
            "avg_r": 29.2
        },
        {
            "rank": 28,
            "name": "동국홀딩스",
            "price": 2015,
            "pbr": 0.16,
            "pbr_r": 3,
            "per": 14.69,
            "per_r": 48,
            "pfcr": 21.14,
            "pfcr_r": 60,
            "psr": 0.14,
            "psr_r": 7,
            "avg_r": 29.5
        },
        {
            "rank": 29,
            "name": "조선내화",
            "price": 14880,
            "pbr": 0.72,
            "pbr_r": 42,
            "per": 5.91,
            "per_r": 20,
            "pfcr": 5.85,
            "pfcr_r": 35,
            "psr": 0.33,
            "psr_r": 22,
            "avg_r": 29.8
        },
        {
            "rank": 30,
            "name": "화천기계",
            "price": 2980,
            "pbr": 0.46,
            "pbr_r": 29,
            "per": 14.56,
            "per_r": 47,
            "pfcr": 3.24,
            "pfcr_r": 20,
            "psr": 0.35,
            "psr_r": 25,
            "avg_r": 30.2
        }
    ],
    "super_value_smallcap": [
        {
            "rank": 1,
            "name": "SJM홀딩스",
            "price": 3490,
            "pbr": 0.16,
            "pbr_r": 1,
            "per": 1.66,
            "per_r": 1,
            "pfcr": 1.23,
            "pfcr_r": 1,
            "psr": 0.24,
            "psr_r": 3,
            "avg_r": 1.5
        },
        {
            "rank": 2,
            "name": "DSR",
            "price": 4240,
            "pbr": 0.27,
            "pbr_r": 4,
            "per": 1.73,
            "per_r": 2,
            "pfcr": 1.75,
            "pfcr_r": 2,
            "psr": 0.22,
            "psr_r": 2,
            "avg_r": 2.5
        },
        {
            "rank": 3,
            "name": "인터지스",
            "price": 2155,
            "pbr": 0.22,
            "pbr_r": 3,
            "per": 5.52,
            "per_r": 4,
            "pfcr": 9.88,
            "pfcr_r": 5,
            "psr": 0.08,
            "psr_r": 1,
            "avg_r": 3.2
        },
        {
            "rank": 4,
            "name": "삼화왕관",
            "price": 25650,
            "pbr": 0.46,
            "pbr_r": 5,
            "per": 5.03,
            "per_r": 3,
            "pfcr": 4.8,
            "pfcr_r": 4,
            "psr": 0.35,
            "psr_r": 4,
            "avg_r": 4.0
        },
        {
            "rank": 5,
            "name": "이화산업",
            "price": 12380,
            "pbr": 0.17,
            "pbr_r": 2,
            "per": 11.67,
            "per_r": 5,
            "pfcr": 22.08,
            "pfcr_r": 6,
            "psr": 0.78,
            "psr_r": 6,
            "avg_r": 4.8
        },
        {
            "rank": 6,
            "name": "화천기계",
            "price": 2980,
            "pbr": 0.46,
            "pbr_r": 6,
            "per": 14.56,
            "per_r": 6,
            "pfcr": 3.24,
            "pfcr_r": 3,
            "psr": 0.35,
            "psr_r": 5,
            "avg_r": 5.0
        }
    ],
    "momentum_value": [
        {
            "rank": 1,
            "name": "OCI",
            "price": 104600,
            "op_growth_qoq": 889.1,
            "op_qoq_r": 5,
            "op_growth_yoy": 171.6,
            "op_yoy_r": 13,
            "ni_growth_qoq": 612.3,
            "ni_qoq_r": 5,
            "ni_growth_yoy": 242.8,
            "ni_yoy_r": 19,
            "avg_r": 10.5
        },
        {
            "rank": 2,
            "name": "이수화학",
            "price": 14590,
            "op_growth_qoq": 845.8,
            "op_qoq_r": 7,
            "op_growth_yoy": 163349.3,
            "op_yoy_r": 1,
            "ni_growth_qoq": 193.4,
            "ni_qoq_r": 24,
            "ni_growth_yoy": 250.9,
            "ni_yoy_r": 18,
            "avg_r": 12.5
        },
        {
            "rank": 3,
            "name": "LX하우시스",
            "price": 32800,
            "op_growth_qoq": 258.7,
            "op_qoq_r": 19,
            "op_growth_yoy": 549.7,
            "op_yoy_r": 5,
            "ni_growth_qoq": 155.7,
            "ni_qoq_r": 30,
            "ni_growth_yoy": 1346.6,
            "ni_yoy_r": 3,
            "avg_r": 14.2
        },
        {
            "rank": 4,
            "name": "삼성전자",
            "price": 362500,
            "op_growth_qoq": 185.1,
            "op_qoq_r": 22,
            "op_growth_yoy": 756.1,
            "op_yoy_r": 4,
            "ni_growth_qoq": 140.4,
            "ni_qoq_r": 34,
            "ni_growth_yoy": 474.3,
            "ni_yoy_r": 7,
            "avg_r": 16.8
        },
        {
            "rank": 5,
            "name": "호텔신라",
            "price": 57600,
            "op_growth_qoq": 595.8,
            "op_qoq_r": 8,
            "op_growth_yoy": 926.4,
            "op_yoy_r": 2,
            "ni_growth_qoq": 136.1,
            "ni_qoq_r": 36,
            "ni_growth_yoy": 197.1,
            "ni_yoy_r": 23,
            "avg_r": 17.2
        },
        {
            "rank": 6,
            "name": "동국제강",
            "price": 9640,
            "op_growth_qoq": 2886.7,
            "op_qoq_r": 2,
            "op_growth_yoy": 403.9,
            "op_yoy_r": 7,
            "ni_growth_qoq": 146.1,
            "ni_qoq_r": 33,
            "ni_growth_yoy": 153.3,
            "ni_yoy_r": 30,
            "avg_r": 18.0
        },
        {
            "rank": 7,
            "name": "SK스퀘어",
            "price": 1700000,
            "op_growth_qoq": 167.2,
            "op_qoq_r": 25,
            "op_growth_yoy": 400.5,
            "op_yoy_r": 8,
            "ni_growth_qoq": 155.6,
            "ni_qoq_r": 31,
            "ni_growth_yoy": 419.4,
            "ni_yoy_r": 9,
            "avg_r": 18.2
        },
        {
            "rank": 8,
            "name": "CR홀딩스",
            "price": 4755,
            "op_growth_qoq": 302.9,
            "op_qoq_r": 15,
            "op_growth_yoy": 52.1,
            "op_yoy_r": 31,
            "ni_growth_qoq": 137.7,
            "ni_qoq_r": 35,
            "ni_growth_yoy": 716.4,
            "ni_yoy_r": 6,
            "avg_r": 21.8
        },
        {
            "rank": 9,
            "name": "조선내화",
            "price": 14880,
            "op_growth_qoq": 293.5,
            "op_qoq_r": 16,
            "op_growth_yoy": 54.3,
            "op_yoy_r": 30,
            "ni_growth_qoq": 597.7,
            "ni_qoq_r": 6,
            "ni_growth_yoy": 115.1,
            "ni_yoy_r": 36,
            "avg_r": 22.0
        },
        {
            "rank": 10,
            "name": "진흥기업",
            "price": 892,
            "op_growth_qoq": 141.6,
            "op_qoq_r": 31,
            "op_growth_yoy": 835.7,
            "op_yoy_r": 3,
            "ni_growth_qoq": 135.3,
            "ni_qoq_r": 37,
            "ni_growth_yoy": 178.5,
            "ni_yoy_r": 25,
            "avg_r": 24.0
        },
        {
            "rank": 11,
            "name": "남성",
            "price": 7000,
            "op_growth_qoq": 304.7,
            "op_qoq_r": 14,
            "op_growth_yoy": -27.5,
            "op_yoy_r": 83,
            "ni_growth_qoq": 815.2,
            "ni_qoq_r": 4,
            "ni_growth_yoy": 9441.3,
            "ni_yoy_r": 1,
            "avg_r": 25.5
        },
        {
            "rank": 12,
            "name": "두산",
            "price": 1634000,
            "op_growth_qoq": 23.8,
            "op_qoq_r": 63,
            "op_growth_yoy": 71.7,
            "op_yoy_r": 20,
            "ni_growth_qoq": 195.4,
            "ni_qoq_r": 22,
            "ni_growth_yoy": 799.1,
            "ni_yoy_r": 5,
            "avg_r": 27.5
        },
        {
            "rank": 13,
            "name": "LG전자",
            "price": 228500,
            "op_growth_qoq": 1635.7,
            "op_qoq_r": 4,
            "op_growth_yoy": 32.9,
            "op_yoy_r": 37,
            "ni_growth_qoq": 238.5,
            "ni_qoq_r": 16,
            "ni_growth_yoy": 14.8,
            "ni_yoy_r": 60,
            "avg_r": 29.2
        },
        {
            "rank": 14,
            "name": "화천기계",
            "price": 2980,
            "op_growth_qoq": 45.5,
            "op_qoq_r": 52,
            "op_growth_yoy": 39.1,
            "op_yoy_r": 36,
            "ni_growth_qoq": 314.5,
            "ni_qoq_r": 13,
            "ni_growth_yoy": 255.2,
            "ni_yoy_r": 17,
            "avg_r": 29.5
        },
        {
            "rank": 15,
            "name": "대우건설",
            "price": 22950,
            "op_growth_qoq": 123.1,
            "op_qoq_r": 34,
            "op_growth_yoy": 68.9,
            "op_yoy_r": 22,
            "ni_growth_qoq": 122.3,
            "ni_qoq_r": 43,
            "ni_growth_yoy": 237.9,
            "ni_yoy_r": 20,
            "avg_r": 29.8
        },
        {
            "rank": 16,
            "name": "GS",
            "price": 71300,
            "op_growth_qoq": 62.1,
            "op_qoq_r": 48,
            "op_growth_yoy": 56.7,
            "op_yoy_r": 29,
            "ni_growth_qoq": 230.0,
            "ni_qoq_r": 19,
            "ni_growth_yoy": 183.6,
            "ni_yoy_r": 24,
            "avg_r": 30.0
        },
        {
            "rank": 17,
            "name": "DL",
            "price": 52400,
            "op_growth_qoq": 858.1,
            "op_qoq_r": 6,
            "op_growth_yoy": 7.1,
            "op_yoy_r": 63,
            "ni_growth_qoq": 169.3,
            "ni_qoq_r": 27,
            "ni_growth_yoy": 162.3,
            "ni_yoy_r": 28,
            "avg_r": 31.0
        },
        {
            "rank": 18,
            "name": "코스모화학",
            "price": 12370,
            "op_growth_qoq": 182.1,
            "op_qoq_r": 23,
            "op_growth_yoy": 528.7,
            "op_yoy_r": 6,
            "ni_growth_qoq": 98.6,
            "ni_qoq_r": 48,
            "ni_growth_yoy": 66.6,
            "ni_yoy_r": 47,
            "avg_r": 31.0
        },
        {
            "rank": 19,
            "name": "신라교역",
            "price": 9110,
            "op_growth_qoq": 475.1,
            "op_qoq_r": 9,
            "op_growth_yoy": 28.6,
            "op_yoy_r": 39,
            "ni_growth_qoq": -7.8,
            "ni_qoq_r": 76,
            "ni_growth_yoy": 815.5,
            "ni_yoy_r": 4,
            "avg_r": 32.0
        },
        {
            "rank": 20,
            "name": "한온시스템",
            "price": 4640,
            "op_growth_qoq": 8.3,
            "op_qoq_r": 72,
            "op_growth_yoy": 361.1,
            "op_yoy_r": 9,
            "ni_growth_qoq": 131.4,
            "ni_qoq_r": 39,
            "ni_growth_yoy": 398.6,
            "ni_yoy_r": 10,
            "avg_r": 32.5
        },
        {
            "rank": 21,
            "name": "DL이앤씨",
            "price": 79200,
            "op_growth_qoq": 149.7,
            "op_qoq_r": 28,
            "op_growth_yoy": 94.3,
            "op_yoy_r": 19,
            "ni_growth_qoq": -22.0,
            "ni_qoq_r": 86,
            "ni_growth_yoy": 429.5,
            "ni_yoy_r": 8,
            "avg_r": 35.2
        },
        {
            "rank": 22,
            "name": "이화산업",
            "price": 12380,
            "op_growth_qoq": 170.0,
            "op_qoq_r": 24,
            "op_growth_yoy": 26.0,
            "op_yoy_r": 41,
            "ni_growth_qoq": 130.4,
            "ni_qoq_r": 40,
            "ni_growth_yoy": 108.4,
            "ni_yoy_r": 38,
            "avg_r": 35.8
        },
        {
            "rank": 23,
            "name": "SJM홀딩스",
            "price": 3490,
            "op_growth_qoq": 420.6,
            "op_qoq_r": 10,
            "op_growth_yoy": -19.1,
            "op_yoy_r": 80,
            "ni_growth_qoq": 1578.4,
            "ni_qoq_r": 2,
            "ni_growth_yoy": 28.1,
            "ni_yoy_r": 55,
            "avg_r": 36.8
        },
        {
            "rank": 24,
            "name": "경동나비엔",
            "price": 70200,
            "op_growth_qoq": 42.6,
            "op_qoq_r": 53,
            "op_growth_yoy": 61.7,
            "op_yoy_r": 27,
            "ni_growth_qoq": 210.2,
            "ni_qoq_r": 21,
            "ni_growth_yoy": 53.8,
            "ni_yoy_r": 48,
            "avg_r": 37.2
        },
        {
            "rank": 25,
            "name": "동국씨엠",
            "price": 5160,
            "op_growth_qoq": 131.5,
            "op_qoq_r": 33,
            "op_growth_yoy": 64.1,
            "op_yoy_r": 24,
            "ni_growth_qoq": 92.1,
            "ni_qoq_r": 50,
            "ni_growth_yoy": 76.6,
            "ni_yoy_r": 45,
            "avg_r": 38.0
        },
        {
            "rank": 26,
            "name": "효성티앤씨",
            "price": 323000,
            "op_growth_qoq": 92.8,
            "op_qoq_r": 43,
            "op_growth_yoy": 11.4,
            "op_yoy_r": 59,
            "ni_growth_qoq": 318.5,
            "ni_qoq_r": 12,
            "ni_growth_yoy": 108.0,
            "ni_yoy_r": 39,
            "avg_r": 38.2
        },
        {
            "rank": 27,
            "name": "신세계",
            "price": 730000,
            "op_growth_qoq": 14.7,
            "op_qoq_r": 67,
            "op_growth_yoy": 49.5,
            "op_yoy_r": 32,
            "ni_growth_qoq": 310.4,
            "ni_qoq_r": 14,
            "ni_growth_yoy": 88.5,
            "ni_yoy_r": 43,
            "avg_r": 39.0
        },
        {
            "rank": 28,
            "name": "이마트",
            "price": 87500,
            "op_growth_qoq": 1909.1,
            "op_qoq_r": 3,
            "op_growth_yoy": 11.9,
            "op_yoy_r": 58,
            "ni_growth_qoq": 168.3,
            "ni_qoq_r": 28,
            "ni_growth_yoy": -5.0,
            "ni_yoy_r": 71,
            "avg_r": 40.0
        },
        {
            "rank": 29,
            "name": "IPARK현대산업개발",
            "price": 20200,
            "op_growth_qoq": 93.8,
            "op_qoq_r": 42,
            "op_growth_yoy": 48.4,
            "op_yoy_r": 34,
            "ni_growth_qoq": 331.6,
            "ni_qoq_r": 10,
            "ni_growth_yoy": -9.0,
            "ni_yoy_r": 75,
            "avg_r": 40.2
        },
        {
            "rank": 30,
            "name": "DSR",
            "price": 4240,
            "op_growth_qoq": 30.4,
            "op_qoq_r": 59,
            "op_growth_yoy": 16.5,
            "op_yoy_r": 54,
            "ni_growth_qoq": 179.3,
            "ni_qoq_r": 25,
            "ni_growth_yoy": 132.9,
            "ni_yoy_r": 32,
            "avg_r": 42.5
        }
    ],
    "momentum_value_smallcap": [
        {
            "rank": 1,
            "name": "남성",
            "price": 7000,
            "op_growth_qoq": 304.7,
            "op_qoq_r": 3,
            "op_growth_yoy": -27.5,
            "op_yoy_r": 8,
            "ni_growth_qoq": 815.2,
            "ni_qoq_r": 2,
            "ni_growth_yoy": 9441.3,
            "ni_yoy_r": 1,
            "avg_r": 3.5
        },
        {
            "rank": 2,
            "name": "화천기계",
            "price": 2980,
            "op_growth_qoq": 45.5,
            "op_qoq_r": 6,
            "op_growth_yoy": 39.1,
            "op_yoy_r": 2,
            "ni_growth_qoq": 314.5,
            "ni_qoq_r": 4,
            "ni_growth_yoy": 255.2,
            "ni_yoy_r": 3,
            "avg_r": 3.8
        },
        {
            "rank": 3,
            "name": "SJM홀딩스",
            "price": 3490,
            "op_growth_qoq": 420.6,
            "op_qoq_r": 1,
            "op_growth_yoy": -19.1,
            "op_yoy_r": 7,
            "ni_growth_qoq": 1578.4,
            "ni_qoq_r": 1,
            "ni_growth_yoy": 28.1,
            "ni_yoy_r": 7,
            "avg_r": 4.0
        },
        {
            "rank": 4,
            "name": "이화산업",
            "price": 12380,
            "op_growth_qoq": 170.0,
            "op_qoq_r": 4,
            "op_growth_yoy": 26.0,
            "op_yoy_r": 3,
            "ni_growth_qoq": 130.4,
            "ni_qoq_r": 7,
            "ni_growth_yoy": 108.4,
            "ni_yoy_r": 5,
            "avg_r": 4.8
        },
        {
            "rank": 5,
            "name": "DSR",
            "price": 4240,
            "op_growth_qoq": 30.4,
            "op_qoq_r": 8,
            "op_growth_yoy": 16.5,
            "op_yoy_r": 4,
            "ni_growth_qoq": 179.3,
            "ni_qoq_r": 5,
            "ni_growth_yoy": 132.9,
            "ni_yoy_r": 4,
            "avg_r": 5.2
        },
        {
            "rank": 6,
            "name": "삼화왕관",
            "price": 25650,
            "op_growth_qoq": 32.7,
            "op_qoq_r": 7,
            "op_growth_yoy": 7.4,
            "op_yoy_r": 5,
            "ni_growth_qoq": 562.6,
            "ni_qoq_r": 3,
            "ni_growth_yoy": 40.5,
            "ni_yoy_r": 6,
            "avg_r": 5.2
        },
        {
            "rank": 7,
            "name": "한국종합기술",
            "price": 4610,
            "op_growth_qoq": -5.6,
            "op_qoq_r": 10,
            "op_growth_yoy": 262.4,
            "op_yoy_r": 1,
            "ni_growth_qoq": -31.4,
            "ni_qoq_r": 10,
            "ni_growth_yoy": 359.9,
            "ni_yoy_r": 2,
            "avg_r": 5.8
        },
        {
            "rank": 8,
            "name": "인터지스",
            "price": 2155,
            "op_growth_qoq": 340.4,
            "op_qoq_r": 2,
            "op_growth_yoy": -58.1,
            "op_yoy_r": 9,
            "ni_growth_qoq": 152.4,
            "ni_qoq_r": 6,
            "ni_growth_yoy": -52.0,
            "ni_yoy_r": 10,
            "avg_r": 6.8
        },
        {
            "rank": 9,
            "name": "대구백화점",
            "price": 4250,
            "op_growth_qoq": 18.6,
            "op_qoq_r": 9,
            "op_growth_yoy": 1.3,
            "op_yoy_r": 6,
            "ni_growth_qoq": 17.8,
            "ni_qoq_r": 8,
            "ni_growth_yoy": 13.7,
            "ni_yoy_r": 8,
            "avg_r": 7.8
        },
        {
            "rank": 10,
            "name": "인팩",
            "price": 5390,
            "op_growth_qoq": 143.4,
            "op_qoq_r": 5,
            "op_growth_yoy": -71.9,
            "op_yoy_r": 10,
            "ni_growth_qoq": -89.8,
            "ni_qoq_r": 11,
            "ni_growth_yoy": -88.8,
            "ni_yoy_r": 11,
            "avg_r": 9.2
        },
        {
            "rank": 11,
            "name": "호전실업",
            "price": 6490,
            "op_growth_qoq": -123.9,
            "op_qoq_r": 12,
            "op_growth_yoy": -132.6,
            "op_yoy_r": 11,
            "ni_growth_qoq": -90.8,
            "ni_qoq_r": 12,
            "ni_growth_yoy": -39.5,
            "ni_yoy_r": 9,
            "avg_r": 11.0
        },
        {
            "rank": 12,
            "name": "에넥스",
            "price": 1577,
            "op_growth_qoq": -32.1,
            "op_qoq_r": 11,
            "op_growth_yoy": -277.4,
            "op_yoy_r": 12,
            "ni_growth_qoq": 3.2,
            "ni_qoq_r": 9,
            "ni_growth_yoy": -309.3,
            "ni_yoy_r": 12,
            "avg_r": 11.0
        }
    ],
    "fscore_value": [
        {
            "rank": 1,
            "name": "두산밥캣",
            "price": 65900,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1263.83
        },
        {
            "rank": 2,
            "name": "이수스페셜티케미컬",
            "price": 81100,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 18.17
        },
        {
            "rank": 3,
            "name": "효성중공업",
            "price": 3693000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 13.57
        },
        {
            "rank": 4,
            "name": "한화엔진",
            "price": 59300,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 8.11
        },
        {
            "rank": 5,
            "name": "한국쉘석유",
            "price": 499500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 5.89
        },
        {
            "rank": 6,
            "name": "한화오션",
            "price": 125100,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 5.62
        },
        {
            "rank": 7,
            "name": "삼성중공업",
            "price": 27700,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 5.47
        },
        {
            "rank": 8,
            "name": "LG이노텍",
            "price": 1283000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 4.99
        },
        {
            "rank": 9,
            "name": "엠앤씨솔루션",
            "price": 90000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 4.63
        },
        {
            "rank": 10,
            "name": "삼성전자",
            "price": 362500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 4.35
        },
        {
            "rank": 11,
            "name": "LG씨엔에스",
            "price": 90000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.97
        },
        {
            "rank": 12,
            "name": "DB하이텍",
            "price": 154500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.84
        },
        {
            "rank": 13,
            "name": "삼성E&A",
            "price": 49700,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.16
        },
        {
            "rank": 14,
            "name": "셀트리온",
            "price": 173600,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.16
        },
        {
            "rank": 15,
            "name": "대한조선",
            "price": 62400,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.1
        },
        {
            "rank": 16,
            "name": "호텔신라",
            "price": 57600,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 2.03
        },
        {
            "rank": 17,
            "name": "에스원",
            "price": 71200,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.62
        },
        {
            "rank": 18,
            "name": "SK텔레콤",
            "price": 95900,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.54
        },
        {
            "rank": 19,
            "name": "현대글로비스",
            "price": 212000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.52
        },
        {
            "rank": 20,
            "name": "경동나비엔",
            "price": 70200,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.24
        },
        {
            "rank": 21,
            "name": "LG전자",
            "price": 228500,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.22
        },
        {
            "rank": 22,
            "name": "에스엘",
            "price": 69400,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.2
        },
        {
            "rank": 23,
            "name": "현대모비스",
            "price": 603000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.08
        },
        {
            "rank": 24,
            "name": "기아",
            "price": 158800,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.01
        },
        {
            "rank": 25,
            "name": "신세계",
            "price": 730000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 1.01
        },
        {
            "rank": 26,
            "name": "HS효성첨단소재",
            "price": 196100,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.96
        },
        {
            "rank": 27,
            "name": "종근당",
            "price": 71100,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.95
        },
        {
            "rank": 28,
            "name": "현대차",
            "price": 601000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.93
        },
        {
            "rank": 29,
            "name": "영원무역",
            "price": 77900,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.8
        },
        {
            "rank": 30,
            "name": "농심",
            "price": 364000,
            "cap_increase_flag": 1,
            "ni_pos_flag": 1,
            "cf_pos_flag": 1,
            "f_score": 3,
            "pbr": 0.76
        }
    ],
    "ncav_value": [
        {
            "rank": 1,
            "name": "SJM홀딩스",
            "price": 3490,
            "ncav": 2026,
            "market_cap": 521,
            "quarter_net_income": 78,
            "gpa": 14.0,
            "debt_ratio": 22.7
        },
        {
            "rank": 2,
            "name": "세원정공",
            "price": 11600,
            "ncav": 3439,
            "market_cap": 1160,
            "quarter_net_income": 487,
            "gpa": 4.0,
            "debt_ratio": 9.5
        },
        {
            "rank": 3,
            "name": "모토닉",
            "price": 10010,
            "ncav": 3780,
            "market_cap": 2175,
            "quarter_net_income": 57,
            "gpa": 6.9,
            "debt_ratio": 13.8
        },
        {
            "rank": 4,
            "name": "신라교역",
            "price": 9110,
            "ncav": 2280,
            "market_cap": 1457,
            "quarter_net_income": 117,
            "gpa": 10.2,
            "debt_ratio": 18.1
        },
        {
            "rank": 5,
            "name": "영원무역홀딩스",
            "price": 176100,
            "ncav": 30738,
            "market_cap": 22811,
            "quarter_net_income": 1942,
            "gpa": 23.4,
            "debt_ratio": 32.1
        },
        {
            "rank": 6,
            "name": "진흥기업",
            "price": 892,
            "ncav": 1369,
            "market_cap": 1297,
            "quarter_net_income": 94,
            "gpa": 13.9,
            "debt_ratio": 124.1
        },
        {
            "rank": 7,
            "name": "HDC현대EP",
            "price": 3915,
            "ncav": 1266,
            "market_cap": 1248,
            "quarter_net_income": 45,
            "gpa": 15.3,
            "debt_ratio": 94.2
        }
    ],
    "ncav_value_gpa": [
        {
            "rank": 1,
            "name": "SJM홀딩스",
            "price": 3490,
            "ncav": 2026,
            "market_cap": 521,
            "quarter_net_income": 78,
            "gpa": 14.0,
            "debt_ratio": 22.7
        },
        {
            "rank": 2,
            "name": "영원무역홀딩스",
            "price": 176100,
            "ncav": 30738,
            "market_cap": 22811,
            "quarter_net_income": 1942,
            "gpa": 23.4,
            "debt_ratio": 32.1
        },
        {
            "rank": 3,
            "name": "진흥기업",
            "price": 892,
            "ncav": 1369,
            "market_cap": 1297,
            "quarter_net_income": 94,
            "gpa": 13.9,
            "debt_ratio": 124.1
        },
        {
            "rank": 4,
            "name": "HDC현대EP",
            "price": 3915,
            "ncav": 1266,
            "market_cap": 1248,
            "quarter_net_income": 45,
            "gpa": 15.3,
            "debt_ratio": 94.2
        }
    ]
};
